use_directory_urls: true
site_name: Metagenomics-Toolkit
docs_dir: ../docs

repo_url: https://github.com/metagenomics/metagenomics-tk
repo_name: Metagenomics-Tk

markdown_extensions:
  - pymdownx.details
  - toc:
      permalink: "&para;"
  - attr_list
  - admonition
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mike

theme:
  name: material
  custom_dir: overrides
  features:
        - navigation.tabs
        - navigation.tabs.sticky
        - content.code.copy
  palette: 
      - scheme: default
        primary: blue grey
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode
      - scheme: slate
        primary: blue grey
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
extra:
  version:
    provider: mike
nav:
  - "Introduction": README.md
  - "Quickstart": quickstart.md 
  - "Getting Started":
    - "Overview": overview.md
    - "Full Pipeline": full_pipeline.md
    - "Aggregation": aggregation.md
  - "Configuration":
    - "Global Pipeline Configuration": configuration.md
    - "Pipeline Input Configuration": pipeline_input.md
    - "Database Configuration": database.md
  - "Modules":
    - modules/introduction.md
    - modules/qualityControl.md
    - modules/annotation.md
    - modules/assembly.md
    - modules/cooccurrence.md
    - modules/dereplication.md
    - modules/fragment_recruitment.md
    - modules/magAttributes.md
    - modules/plasmids.md
    - modules/metabolomics.md
    - modules/readMapping.md
    - modules/export.md
  - "Tutorials":
    - "Tutorial (Basics)": 
      - "Introduction": tutorials/tutorial1/introduction.md 
      - "Quality Control": tutorials/tutorial1/quality_control.md 
      - "Assembly": tutorials/tutorial1/assembly.md
      - "Assembly Evaluation": tutorials/tutorial1/assembly_evaluation.md
      - "Binning": tutorials/tutorial1/binning.md
      - "Assessing Bin Quality": tutorials/tutorial1/bin_quality.md
      - "Classification": tutorials/tutorial1/classification.md
      - "Annotation": tutorials/tutorial1/annotation.md
  - "Developer":
    - developer_guidelines.md
    - pipeline_specification.md
    - module_specification.md
