style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/pbelmann/meta-omics-toolkit
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - doc
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      doc: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
