ADDITIONAL_RGI_PARAMS="!{params.steps?.annotation?.rgi?.additionalParams}"

# Check developer documentation
CARD_JSON=""
if [ -z "!{EXTRACTED_DB}" ] 
then
     DATABASE=!{params.polished.databases}/rgi
     LOCK_FILE=${DATABASE}/lock.txt

# Check if access and secret keys are necessary for s5cmd
     if [ ! -z "!{S3_rgi_ACCESS}" ]
     then
       export AWS_ACCESS_KEY_ID=!{S3_rgi_ACCESS}
       export AWS_SECRET_ACCESS_KEY=!{S3_rgi_SECRET}
     fi

     # Download CARD database
     mkdir -p ${DATABASE}
     flock ${LOCK_FILE} concurrentDownload.sh --output=${DATABASE} \
      --link=!{DOWNLOAD_LINK} \
      --httpsCommand="wgetStatic --no-check-certificate -qO- !{DOWNLOAD_LINK} | tar -xvj " \
      --s3DirectoryCommand="s5cmd !{S5CMD_PARAMS} cp --concurrency !{task.cpus}  !{DOWNLOAD_LINK} . " \
      --s3FileCommand="s5cmd !{S5CMD_PARAMS} cat --concurrency !{task.cpus} !{DOWNLOAD_LINK} | tar -xvj " \
--s5cmdAdditionalParams="!{S5CMD_PARAMS}" \
      --localCommand="tar -xvjf !{DOWNLOAD_LINK}" \
      --expectedMD5SUM=!{MD5SUM}

      CARD_JSON="$(readlink -f ${DATABASE}/out/card.json)"
else
      CARD_JSON="!{EXTRACTED_DB}"
fi

# gunzip (if required) and strip '*' sign from amino acid files
zcat -f !{fasta} | sed 's/*//g' > input.faa

mkdir output
OUTPUT_ID=!{binID}.rgi
RGI_OUTPUT=output/${OUTPUT_ID}
# load CARD database and run rgi
rgi load --card_json ${CARD_JSON} --local
rgi main --input_sequence input.faa \
            --output_file ${RGI_OUTPUT} --input_type protein --local \
            --alignment_tool DIAMOND --num_threads !{task.cpus} --clean ${ADDITIONAL_RGI_PARAMS}

# Fix for ownership issue https://github.com/nextflow-io/nextflow/issues/4565
chmod a+rw -R output
chmod a+rw -R localDB

RGI_OUT_TMP=!{binID}.rgi.tmp.tsv
RGI_OUT=!{binID}.rgi.tsv
# Produce files only if there is an actual output
if [ $(tail -n +2 ${RGI_OUTPUT}.txt | wc -l) -gt 0 ]; then 

  #  add sample and binid information to rgi output
  sed  '1 s/^/SAMPLE\tBIN_ID\t/g' ${RGI_OUTPUT}.txt  \
   | sed "2,$ s/^/!{sample}\t!{binID}\t/g" > ${RGI_OUT_TMP}

  # ORF_ID generated by rgi contains ORF names with whitespaces (e.g.: "POGDFCMJ_00141 Methionyl-tRNA formyltransferase")
  # The following lines shortens the ID (e.g.: POGDFCMJ_00141)
  paste -d$"\t" <(cut -f 3 ${RGI_OUT_TMP} | cut -d ' ' -f 1) ${RGI_OUT_TMP} \
    | sed '1 s/ORF_ID/ORF_SHORT_ID/' > ${RGI_OUT}

  # RGI Heatmap fails because of the following error: https://github.com/arpcard/rgi/issues/188
  trap 'if [ "$?" == 1 ] && ( grep -q "ValueError: zero-size array to reduction operation fmin which has no identity" stderr.log ); then echo "Heatmap could not be produced"; exit 0; fi' EXIT
  rgi heatmap --input output --output ${OUTPUT_ID} 2> >(tee -a stderr.log >&2)
fi

