name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]
    paths-ignore: 
       - 'docker/**/VERSION'

env:
  WORK_DIR: "/vol/spool"

jobs:
  merge_job:
  # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: [ self-hosted, slurm]
    steps:
    - run: |
        rm -rf  ${WORK_DIR}/${{ github.head_ref }}*

  close_job:
  # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: [ self-hosted, slurm]
    steps:
    - run: |
        rm -rf ${WORK_DIR}/${{ github.head_ref }}*
