name: Docker

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'docker/**/VERSION'
jobs:

  push:
    runs-on: [self-hosted, dockerPush]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log into docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and publish docker images
        run: |
            make build_publish_docker ${{ github.event.before }} ${{ github.sha }} ${{ secrets.DOCKER_REGISTRY_URL }} ${{ secrets.REPOSITORY }}
  
