name: Docker

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'docker/**/VERSION'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Force Install GIT latest
        run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish docker images
        run: |
            make build_publish_docker ${{ github.event.before }} ${{ github.sha }} ${{ secrets.DOCKER_REGISTRY_URL }} ${{ secrets.REPOSITORY }}
  
