name: Build and push Docker images

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'docker/**/VERSION'
jobs:
  push:
    runs-on: [ self-hosted, dockerPush ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and publish docker images for quay.io
        run: |
            make build_publish_docker COMMIT_START=${{ github.event.before }} COMMIT_END=${{ github.sha }} DOCKER_REPOSITORY=${{ secrets.QUAY_REPOSITORY }}
