name: "Run Tests against real samples"
on: [workflow_dispatch]
jobs:
  build_job:
    runs-on: [self-hosted, prodTest]
    steps:
      - uses: actions/checkout@v2
      - name: "Run full pipeline mode with all samples"
        run: |
          bash ./scripts/test_fullPipeline.sh \
          " -c /vol/spool/aws.config --databases=/vol/scratch/databases/  --logDir s3://toolkit-dev-benchmark " \
          ./default/fullPipeline_illumina_nanpore.yml "${WORK_DIR}/${{ github.head_ref }}" slurm || exit 1


