
name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  full_pipeline:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: full-pipeline
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 

      - name: Test Full Pipeline Run
        run: |
          bash ./scripts/test_fullPipeline.sh \
          " --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " \
          "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

      - name: Test Full Pipeline run that ends with magAttributes
        run: |
          bash ./scripts/test_fullPipeline.sh \
          "  --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " \
          example_params/fullPipeline_fraction/fullPipeline_fraction_magAttributes.yml "/mnt/work/work/${{ github.head_ref }}" || exit 1
      - name: Test Full Pipeline run that ends with binning
        run: |
          bash ./scripts/test_fullPipeline.sh "" example_params/fullPipeline_fraction/fullPipeline_fraction_binning_metabinner.yml \
          "/mnt/work/work" || exit 1

          #      - name: Test Aggregation Pipeline run based on per samples results.
          #        run: |
          #          bash ./scripts/test_fullPipelineAggregate.sh " -c  test_data/assets/aws.config " "" "/mnt/work/work/${{ github.head_ref }}"|| exit 1

      - name: Test if SRA S3 Entrypoint works 
        run: |
          bash ./scripts/test_SRA.sh " -c  test_data/assets/aws.config " || exit 1

      - name: Test if SRA S3 Input module works 
        run: |
          bash ./scripts/test_fullPipeline.sh   " -c  test_data/assets/aws.config "  ./example_params/fullPipelineSRAQC.yml || exit 1


  mag_attributes:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: mag_attributes
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test MAG Attributes
        run: |
          bash ./scripts/test_magAttributes.sh \
          "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " \
          "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

      - name: Test MAG Attributes Fraction
        run: |
          bash ./scripts/test_magAttributes.sh \
          "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " \
          example_params/magAttributes_fraction/magAttributes.yml "/mnt/work/work/${{ github.head_ref }}" || exit 1
  dereplication:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [mag_attributes]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Dereplication
        run: |
          bash ./scripts/test_dereplication.sh "" "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

  readmapping:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [dereplication]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Read Mapping
        run: |
          bash ./scripts/test_readMapping.sh "" "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

  assembly:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [readmapping]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Assembly
        run: |
          bash ./scripts/test_assembly.sh "" "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

  cooccurrence:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [assembly]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Cooccurrence
        run: |
          bash ./scripts/test_cooccurrence.sh "" "" "/mnt/work/work/${{ github.head_ref }}" || exit 1

  fragment_recruitment:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 700
    needs: [cooccurrence]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: ${{github.head_ref}}-nextflow-cache
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Fragment Recruitment
        run: |
          bash ./scripts/test_fragmentRecruitment.sh "" "" "/mnt/work/work/${{ github.head_ref }}" || exit 1
