
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  full_pipeline:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: full-pipeline
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 

      - name: Test Full Pipeline Run
        run: |
          bash ./scripts/test_fullPipeline.sh " --input=/mnt/nextflow_cache/test/reads/small/reads_split.tsv --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  || exit 1

      - name: Test Full Pipeline run that ends with magAttributes
        run: |
          bash ./scripts/test_fullPipeline.sh " --input=/mnt/nextflow_cache/test/reads/small/reads_split.tsv --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " example_params/fullPipeline_fraction/fullPipeline_fraction_magAttributes.yml  || exit 1

  mag_attributes:
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: mag_attributes
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test MAG Attributes
        run: |
          bash ./scripts/test_magAttributes.sh "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  || exit 1

      - name: Test MAG Attributes Fraction
        run: |
          bash ./scripts/test_magAttributes.sh "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  example_params/magAttributes_fraction/magAttributes.yml  || exit 1

  dereplication:
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Dereplication
        run: |
          bash ./scripts/test_dereplication.sh || exit 1

  Other:

    needs: [mag_attributes]

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: ${{github.head_ref}}-nextflow-cache
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 

      - name: Test Fragment Recruitment
        run: |
          bash ./scripts/test_ci_fragmentRecruitment.sh || exit 1


