
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  full_pipeline:
    timeout-minutes: 700
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: full-pipeline
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 

      - name: Test Full Pipeline Run
        run: |
          bash ./scripts/test_fullPipeline.sh "  --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  || exit 1

      - name: Test Full Pipeline run that ends with magAttributes
        run: |
          bash ./scripts/test_fullPipeline.sh "  --steps.magAttributes.checkm.database=/mnt/checkm --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 " example_params/fullPipeline_fraction/fullPipeline_fraction_magAttributes.yml  || exit 1
      - name: Test Full Pipeline run that ends with binning
        run: |
          bash ./scripts/test_fullPipeline.sh "" example_params/fullPipeline_fraction/fullPipeline_fraction_binning_metabinner.yml || exit 1

      - name: Test Aggregation Pipeline run based on per samples results.
        run: |
          bash ./scripts/test_fullPipelineAggregate.sh " -c  test_data/assets/aws.config " || exit 1

  mag_attributes:
    timeout-minutes: 700
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: mag_attributes
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test MAG Attributes
        run: |
          bash ./scripts/test_magAttributes.sh "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  || exit 1

      - name: Test MAG Attributes Fraction
        run: |
          bash ./scripts/test_magAttributes.sh "  --steps.magAttributes.checkm.database=/mnt/checkm  --steps.magAttributes.gtdb.database=/mnt/gtdb/release202 "  example_params/magAttributes_fraction/magAttributes.yml  || exit 1

  dereplication:
    timeout-minutes: 700
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Dereplication
        run: |
          bash ./scripts/test_dereplication.sh || exit 1

  readmapping:
    timeout-minutes: 700
    needs: [dereplication]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Read Mapping
        run: |
          bash ./scripts/test_readMapping.sh || exit 1

  assembly:
    timeout-minutes: 700
    needs: [readmapping]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Assembly
        run: |
          bash ./scripts/test_assembly.sh || exit 1

  cooccurrence:
    timeout-minutes: 700
    needs: [assembly]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: dereplication
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Cooccurrence
        run: |
          bash ./scripts/test_cooccurrence.sh || exit 1

  fragment_recruitment:
    timeout-minutes: 700
    needs: [cooccurrence]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: ${{github.head_ref}}-nextflow-cache
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Fragment Recruitment
        run: |
          bash ./scripts/test_ci_fragmentRecruitment.sh || exit 1

  annotation:
    timeout-minutes: 700
    needs: [full_pipeline]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache nextflow cache
        uses: actions/cache@v2
        with:
           path: ${{github.workspace}}/.nextflow
           key: ${{github.head_ref}}-nextflow-cache
      - name: clean up existing inputs directory
        run: |
          rm -rf /mnt/nextflow_cache/* 
      - name: Test Annotation
        run: |
          bash ./scripts/test_ci_annotation.sh || exit 1
